# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
MCpbt <- function(iter, burnIn, thin, seed, piTotPrior, ohnc, piTotInitial, oUTInitial, groups, nPBT, GSI_values, gsiUT, pi_gsiInitial, prior_pi_gsi, ohnc_gsi, values, pi_VInitial, pi_Vohnc, pi_Vprior, v_ut, initZ, t, valuesOth, pi_VInitialOth, pi_VohncOth, pi_VpriorOth, v_utOth) {
    .Call(`_fishCompTools_MCpbt`, iter, burnIn, thin, seed, piTotPrior, ohnc, piTotInitial, oUTInitial, groups, nPBT, GSI_values, gsiUT, pi_gsiInitial, prior_pi_gsi, ohnc_gsi, values, pi_VInitial, pi_Vohnc, pi_Vprior, v_ut, initZ, t, valuesOth, pi_VInitialOth, pi_VohncOth, pi_VpriorOth, v_utOth)
}

#' @export
propClipped <- function(Nclip, Nunclip, NumResults, seed, clipPrior = as.numeric( c(1,1))) {
    .Call(`_fishCompTools_propClipped`, Nclip, Nunclip, NumResults, seed, clipPrior)
}

